### ISSUE TITLE
feature: please add ZST support for board packages

### ISSUE THREAD

**Issue by ckahlo** [Sloeber/arduino-eclipse-plugin#1622] opened 2024-02-04 17:20 UTC
installed version:  Sloeber 4.4.2.202311302107 io.sloeber.product
issue: people are migrating from BZ2 to ZST image format for board packages.
example: https://forum.pjrc.com/index.php?threads/should-we-use-bz2-or-zst-or-xz-compression-for-teensy-downloads-in-arduino-ide-2-2-x.73981/

error reported by Sloeber:
Installing Arduino Board Platforms
Failed to install Teensy
Archive format not supported.

Would it be possible to add support for ZST packages? Or is there anything else one can do to fix this?
(besides repackaging and adding a custom platform.json)

Thanks and best regards,
Christian

**Comment by jantje** [comment] 2024-02-04 17:31
I'm currently running tests to release 4.4.3 for this particular issue
You can find the current version here https://github.com/Sloeber/arduino-eclipse-plugin/actions/runs/7764103167

This is a duplicate of #1611 (which is closed as it is in the nightly)

**Closed by jantje** 2024-02-04 17:31 UTC
