### ISSUE TITLE
Sloeber won't finish installation in Eclipse

### ISSUE THREAD

**Issue by grijspetje** [Sloeber/arduino-eclipse-plugin#1245] opened 2020-11-03 11:38 UTC
Sloeber is not able to download Arduino stuf...
see attatched error log
[Sloeber.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/5480936/Sloeber.log)

**Comment by jantje** [comment] 2020-11-03 13:06
duplicate of #1240 #1196

**Closed by jantje** 2020-11-03 13:06 UTC
Labels: status: duplicate
