### ISSUE TITLE
Release testing 4.4 test case 4.3 -> 4.4 Win10 (warning level not taken into account properly)

### ISSUE THREAD

**Issue by ArminJo** [Sloeber/arduino-eclipse-plugin#1333] opened 2021-04-15 21:33 UTC
AVR projects which were closed in 4.3 and opened under 4.4 loose the` Use alternative size command`? check, i.e. we have `Config.Release.compile.sloeber.size.switch=false`.
If this cannot be fixed, it should be noted in the Upgrade_Instructions.txt , so that the user must not seach for the reason like I did, but can edit the .sproject file, which is much faster, especially for multi configuration projects.

P.s. can the old 4.3 org.eclipse.cdt.core.prefs files be removed (or stripped)

**Comment by jantje** [comment] 2021-04-15 22:58
>projects which were closed in 4.3 and opened under 4.4 loose the Use alternative size command? check, i.e. we have Config.Release.compile.sloeber.size.switch=false

Thanks for the report. I'll investigate

> can the old 4.3 org.eclipse.cdt.core.prefs files be removed (or stripped)

I'm not sure which files you mean. Are this workspace files, project files or install files?

**Comment by ArminJo** [comment] 2021-04-15 23:00
> I'm not sure which files you mean. Are this workspace files, project files or install files?

the <project root>/.settings/org.eclipse.cdt.core.pref where the old board settings were located.

**Comment by jantje** [comment] 2021-04-15 23:14
>the /.settings/org.eclipse.cdt.core.pref where the old board settings were located.

So you are talking about the project preference settings.
If you only have set Sloeber values they should be empty and gone
If you have set other CDT preferences they should still be in these files

**Comment by ArminJo** [comment] 2021-04-15 23:40
Thanks for the reply, mostly I have no other than Sloeber preferenced set in an project, but since I know, I can check for it 😀 .

**Comment by jantje** [comment] 2021-04-17 13:57
>projects which were closed in 4.3 and opened under 4.4 loose the Use alternative size command? check, i.e. we have Config.Release.compile.sloeber.size.switch=false

I checked and if the original value of "show all warnings" was true it is still true after upgrade.
I even have a unit test testing this

however I see that the flag is not taken into account properly

**Comment by ArminJo** [comment] 2021-04-17 18:53
Where are nightly builds to test?
I can not compile it for myself now.

**Comment by jantje** [comment] 2021-04-17 18:58
The nightly is updated every night.
Should be available from the nightly tomorrow.
I hope to finish #1335 tonight as well

**Comment by ArminJo** [comment] 2021-04-17 19:02
But where can I download the nightly? I my be a bit of a fool, but I did not found it yet.

**Comment by jantje** [comment] 2021-04-17 19:56
http://eclipse.baeyens.it/nightly.php
add this site to your update sites in windows->preferences->update sites
and run updates

**Comment by ArminJo** [comment] 2021-04-18 10:57
After updating right now I get:
![2021-04-18 12_51_01-Problem Occurred](https://user-images.githubusercontent.com/3881884/115143007-0f036380-a045-11eb-9220-7d0d0c6adb39.png)
I use working sets and cannot access any files in these anymore.
But even in the plain project view no project file is shown 😢 .
![2021-04-18 12_51_19-WORKSPACE_SLOEBER_44 - Sloeber](https://user-images.githubusercontent.com/3881884/115143042-3e19d500-a045-11eb-9b54-9ba2df174181.png)

**Comment by jantje** [comment] 2021-04-18 13:25
Can you zip and provide me your workspace as is before upgrade so I can try?

**Comment by ArminJo** [comment] 2021-04-18 13:58
It is here.
https://www.dropbox.com/sh/gbzu4ow2jndyzme/AACzyi1CBwybfdfF_ktU9rIPa?dl=0
But 1.3 GByte and still uploading.

**Comment by jantje** [comment] 2021-04-18 14:03
Thinking about this a bit more I think I know what the problem is.
I assume that you have partially migrated that is you already have a .sproject and that .sproject contains warning_level=true
With the new nightly this will cause problems as it has to be NONE ALL MORE or CUSTOM
I assume that the other problems are consequences of sloeber "crashing" on this error.
I think it is a good idea to make sloeber mlore resiliant for badly formatted .sproject files and sloeber.cfg file

**Comment by jantje** [comment] 2021-04-18 18:34
The dropbox map is still empty
I made a fix for .sproject containing a wrong value like true or false

**Comment by ArminJo** [comment] 2021-04-18 19:07
> The dropbox map is still empty

Sorry, I was not at home and the upload was interrupted.

> I made a fix for .sproject containing a wrong value like true or false

THANKS! I will test it tomorrow

**Comment by jantje** [comment] 2021-05-23 23:36
I think we can close this issue. I tested and the warning levels (like in Arduino IDE) are now selectable and custom and they work fine on my system
Please reopen if not fixed

**Closed by jantje** 2021-05-23 23:36 UTC
Labels: beta 4.4
