### ISSUE TITLE
Failed to config Sloeber

### ISSUE THREAD

**Issue by comtronic-99** [Sloeber/arduino-eclipse-plugin#1286] opened 2021-01-22 22:30 UTC
After installing latest Windows 4.3.3 stable and starting sloeber the first time I run into a "failed to config Sloeber" Problem

![grafik](https://user-images.githubusercontent.com/77862286/105555266-4f369c80-5d09-11eb-9ced-a9b6d8d0d00b.png)

which states: Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2"

Even trying several times, I get this download error.

Manually I can open the download site but cannot see the "ArduinoCore-mbed-nonexistant.tar.bz2"

**Comment by jantje** [comment] 2021-01-22 23:06
This is duplicate of #1196

Sloeber does not come with any platform (read boards) so it tries to install a platform and the platform sloeber tries to install has been deprecated.
Solution
install the platform of your choice at window->preferences->arduino->platform&boards
press on the > untill you can select a version you want to install
select apply and close and wait for it to finish (look at bottom right)
You are ready to roll

**Closed by jantje** 2021-01-22 23:06 UTC
Labels: status: duplicate
