### ISSUE TITLE
Type fatal error: iostream: No such file or directory

### ISSUE THREAD

**Issue by guillotl** [Sloeber/arduino-eclipse-plugin#758] opened 2017-05-31 15:33 UTC
Hi, I had some problem with MySensors Library when I'm compiling with Eclipse IDE.
In Arduino IDE, there is no problem but with Eclipse IDE I had  some problem with this library.

Indeed, this library call a .h which contains functions like iostream and which returns in error at compilation. Is there a way to avoid this?

#include <iostream>
#include <cstdio>
#include <unistd.h>

Cordially,

**Comment by jantje** [comment] 2017-06-01 10:13
duplicate of #712
Note that this is fixed in the branch library improvements which will be integrated into master into the comming weeks.

**Closed by jantje** 2017-06-01 10:13 UTC
Labels: status: duplicate
