### ISSUE TITLE
Commandline define with string is in code replaced as identifier in stead of string

### ISSUE THREAD

**Issue by Bascy** [Sloeber/arduino-eclipse-plugin#1052] opened 2018-12-16 18:14 UTC
Compiling the ESPmDNS library from arduinoe_esp32 an error occurs where ARDUINO_VARIANT is replaced by its command line definition.

The command line specifies: `-DARDUINO_VARIANT="esp32"`
the code is the following:

`void MDNSResponder::enableArduino(uint16_t port, bool auth){
    mdns_txt_item_t arduTxtData[4] = {
        {(char*)"board"         ,(char*)ARDUINO_VARIANT},
        {(char*)"tcp_check"     ,(char*)"no"},
        {(char*)"ssh_upload"    ,(char*)"no"},
        {(char*)"auth_upload"   ,(char*)"no"}
    };`

Because ARDUINO_VARIANT gets replaced with `esp32` in stead of `"esp32"` the compilation fails with "unknown identifier esp32"

**Comment by jantje** [comment] 2018-12-16 22:00
this is a duplicate of #1028
I would love to see esp to fix this by using the workaround I describe

**Closed by jantje** 2018-12-16 22:00 UTC
