### ISSUE TITLE
Sloeber does not compile some examples for ESP32

### ISSUE THREAD

**Issue by aiotech-pub** [Sloeber/arduino-eclipse-plugin#1422] opened 2021-12-16 00:27 UTC
I am using Sloeber (product) on Win7 and Win10 (2 different PCs) and the installation is used only for ESP32 MCUs.
Sloeber does not compile some of the ESP32 examples. For instance it does not compile the BLE_server example (File/Examples/ESP32 BLE Arduino/BLE_server

The error:
In file included from C:\Prog\Sloeber-2\arduinoPlugin\packages\esp32\hardware\esp32\2.0.1\cores\esp32/Arduino.h:33,
                 from ..\sloeber.ino.cpp:7:
C:\Prog\Sloeber-2\arduinoPlugin\packages\esp32\hardware\esp32\2.0.1/tools/sdk/esp32/include/freertos/include/freertos/FreeRTOS.h:57:10: fatal error: FreeRTOSConfig.h: No such file or directory
 #include "FreeRTOSConfig.h"
          ^~~~~~~~~~~~~~~~~~

so seems there are some problems to include the needed directories.

**Comment by jantje** [comment] 2021-12-16 01:06
duplicate of #1295

**Closed by jantje** 2021-12-16 01:06 UTC
