### ISSUE TITLE
Can't install the software - dead link

### ISSUE THREAD

**Issue by fneves78** [Sloeber/arduino-eclipse-plugin#1235] opened 2020-10-23 12:21 UTC
When trying to install the software on my Debian laptop and running it for the first time, there is an error :

Failed to configer Sloeber
Failed to install [DEPRECATED] Arduino mbed-enabled Boards
Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2".
Failed to download url http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2 error code is: 404

![image](https://user-images.githubusercontent.com/38001761/97002760-ba21dd00-153a-11eb-8dfb-46951e25431b.png)

My internet connection has no problem.
Can you help ?

**Comment by jantje** [comment] 2020-10-23 12:27
duplicate of #1230

**Closed by jantje** 2020-10-23 12:27 UTC

**Comment by amerging** [comment] 2020-12-14 01:01
Is anyone resolved this issue as we are looping with duplicate - post , not solution to this ..
