### ISSUE TITLE
Sloeber plugin won't install on 2021-06 after most recent update

### ISSUE THREAD

**Issue by eshicks4** [Sloeber/arduino-eclipse-plugin#1361] opened 2021-07-12 05:50 UTC
====================WORKAROUND===============
There are a couple of ways to work around this issue. Here are 2

1) make sure you have following update sites before installing sloeber
https://download.eclipse.org/releases/latest/
http://download.eclipse.org/eclipse/updates/latest
https://download.eclipse.org/nebula/releases/latest/ 
http://eclipse.baeyens.it/update/V4/stable

2) Try to install sloeber using either the marketplace or install new software
This will fail (but will add the update sites above to the update sites)
Restart eclipse (needed to clean caches)
try again (this should work)

3) add the plugin (not the product) to an existing eclipse install. 
=============================================

An update came through yesterday (2021-11-07) which doesn't appear compatible with the current version 2021-06.  I've tried multiple times from completely fresh installs of different "flavors" and the fewest errors I've gotten has been from the C/C++ variety:

An error occurred while collecting items to be installed
session context was:(profile=_Users_ehicks_Applications_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.nebula.cwt,1.1.0.202011020719
No repository found containing: osgi.bundle,org.eclipse.nebula.widgets.cdatetime,1.5.0.202011020719
No repository found containing: osgi.bundle,org.hamcrest.core,1.3.0.v20180420-1519
No repository found containing: osgi.bundle,org.junit,4.13.0.v20200204-1500

I'm also attaching an export of my install sources.  It's from one of today's fresh installs but after having installed a few other packages to make sure it was just Sloeber that was having issues.

[bookmarks.xml.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/6798819/bookmarks.xml.txt)

If you need any other info please let me know.  Thanks

**Comment by jantje** [comment] 2021-07-12 15:28
I tested with downloading Sloeber version V.4.3.3 and upgrading.
Apart from having to replace the jre because of the java update (causing me to have to restart 2 times) all went well.

Can you please be more precise on what you are trying to do?
What do you men with 2021-06? There has not been a Sloeber release on 2021-06

**Comment by eshicks4** [comment] 2021-07-12 21:36
2021-06 is the latest Eclipse.  Installing Sloeber product via the Marketplace had worked until yesterday.

I haven't  been able to get the customized Eclipse version to work at all.  I'm on MacOS Big Sur with jdk1.8.0_291.jdk installed.  When I try to launch it I just get an alert window that says "Failed to create the Java Virtual Machine".  Attempting to run the binary directly I see this:

iMac:~ user$ Applications/Sloeber.app/Contents/MacOS/sloeber-ide
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/lib/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.

The binary just hangs from there until I cntl-c out of it.  It isn't lying about the file not being there but I'm not sure why it wasn't installed with the rest of the JDK or what I need to install to get it.

**Comment by eshicks4** [comment] 2021-07-12 21:46
BTW, I did see the note that the newer Sloebers need JDK11 but I'm not sure how to convince it to use it.  It is installed and a link to it is in /Libaray/Java/JavaVirtualMachines but the trick it convincing the software to use it instead of JDK8.

```
iMac:~ user$ ls -l /Library/Java/JavaVirtualMachines/
drwxr-xr-x  3 root  wheel   96 Jul 12 01:32 jdk1.8.0_291.jdk
lrwxr-xr-x  1 root  wheel   33 Jun 22 10:20 openjdk.jdk -> /usr/local/Cellar/openjdk/16.0.1/
lrwxr-xr-x  1 root  wheel   37 Jun 22 10:21 openjdk@11.jdk -> /usr/local/Cellar/openjdk@11/11.0.10/
```

**Comment by jantje** [comment] 2021-07-12 22:09
this page explains how you can set the java path
https://wiki.eclipse.org/Eclipse.ini
having a jre folder works as well if you have enough disk space
![afbeelding](https://user-images.githubusercontent.com/1175841/125362102-9cb5cd00-e36e-11eb-8878-ae98ed513c7a.png)

**Comment by eshicks4** [comment] 2021-07-13 00:16
The JRE subdirectory part didn't work for me as it still wanted to use the system JDK8; however, forcing the path to JDK11 in the ini file did.  Still kind of bummed that I need to split across 2 IDEs but at least I can push off learning PlatformIO a bit longer.  Feel free to do whatever you like with this issue report.  Thanks!

**Comment by jantje** [comment] 2021-07-13 13:03
The jre subfolder is a standard eclipse way to do things. This should work though.

>Still kind of bummed that I need to split across 2 IDEs 

What do you mean by that?

**Comment by florianfa** [comment] 2021-08-19 12:12
I'm facing the same issue here.

**Comment by wimjongman** [comment] 2021-08-19 14:13
https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos

**Comment by florianfa** [comment] 2021-08-19 14:26
Hi wim,

JDK11 also won't work. I,m actually using the following environment:

Eclipse Version: 2021-06
Sloeber Version: 4.4.0
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

Florian

**Comment by wimjongman** [comment] 2021-08-19 14:59
@florianfa what is exactly your problem? Please attach logs and stuff (attach, not paste in comment). Cheers.

**Comment by Kilill** [comment] 2021-09-08 14:31
Seems i have the same issue? 

Trying to install the plugin from the marketplace on a fresh install of eclipse:

i get the following error
Installing software has enountered a problem.

```
An error occurred while collecting items to be installed
session context was:(profile=E__eclipse_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,jnr.x86asm,1.0.2.v201505052040
No repository found containing: osgi.bundle,org.eclipse.nebula.cwt,1.1.0.202011020719
No repository found containing: osgi.bundle,org.eclipse.nebula.widgets.cdatetime,1.5.0.202011020719
No repository found containing: osgi.bundle,org.hamcrest.core,1.3.0.v20180420-1519
No repository found containing: osgi.bundle,org.junit,4.13.0.v20200204-1500
```


OS: Windows 10

Eclipse version: 
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

Attaching parts of the configuration dump from eclipse
[eclipseDump.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/7129611/eclipseDump.txt)

**Comment by jantje** [comment] 2021-09-08 15:52
From the log I would assume you do not have nebula in your update sites
http://download.eclipse.org/nebula/releases/latest/
This should resolve the 2 nebula repositories and may introduce new ones
I'm not sure where the others should be found.
Do you have http://download.eclipse.org/releases/latest/ as update site? I mean junit seems pretty common in eclipse.

**Comment by Kilill** [comment] 2021-09-08 17:40
Thanks, you was almost right, the Nebula repository was there and did contain the actual files. After a lot of trial and error i disabled the Nebula site and lo and behold it installed without complaining.

Tried to reenable the Nebula site after and sure enough, it fails.

So it seems the eclipse-21-06 install sets up some weird repositories

Thanks for the help!

**Comment by jantje** [comment] 2021-09-08 23:20
@Kilill 
The whole update site ecosystem is still unknown territory to me. I simply even can't get my head around how it is supposed to work in a multiple update site scenario as the add sloeber to standard eclipse.
Basically I think it is a miracle it works correctly so often.
Anyway that is also why we created the project that is one download with all the correct plugins in one go.

**Comment by btoland** [comment] 2021-09-10 10:01
I'm having the same problem trying to install the plugin into a fresh eclipse 2021-06 CDT install.

I'm getting exactly the same errors as @Kilill.  Tried the solution of removing and adding back in the Nebula repository.  Nebula errors go away when repository removed but others remain... and come back when Nebula re-added.  Checked the basic update site urls too - all good -as expected from a fresh install.

Any chance we could get a link to the previous (or older) release of the plugin?  I think archive versions on the website are the Sloeber Product (I could be wrong there?) but I need to create a custom bundle for teaching.

I tried fresh older versions of eclipse 10 CDT too and got same results.  Tried eclipse 9 CDT as well but plugin won't install on that - tries to upgrade to eclipse 10.  Also tried on a fresh eclipse Java 2021-06 - same errors as CDT 2021-06.

It would be great to be able to select different versions of the plugin to help hunt down incompatibility issues?

Win 10 on Virtualbox guest, macOS host.
OpenJDK 11, HotSpot JRE
Eclipse version 2021-06 CDT 10.3.2

**Comment by jantje** [comment] 2021-09-10 10:42
>I'm getting exactly the same errors as @Kilill. Tried the solution of removing and adding back in the Nebula repository. Nebula errors go away when repository removed but others remain...

And these are?

>I think archive versions on the website are the Sloeber Product (I could be wrong there?) but I need to create a custom bundle for teaching.

Why don't you take the product and start from there to build your custom bundle?
The product is eclipse +egit + cdt + sloeber + ...

Alternatively; check the master out from github go to the branch that is linked to the release you want and build with maven. That will give you the update site and the product.
The some old products install zips/archives are available but I don't want to go into the nightmare of old update sites.
Update sites are a nightmare and that is why we created the self contained product and do not support update sites

>Tried eclipse 9 CDT as well but plugin ...

https://github.com/Sloeber/arduino-eclipse-plugin/issues/1263
A similar issue exists with java versions 

>It would be great to be able to select different versions of the plugin to help hunt down incompatibility issues?

I don't see any new incompatibility issues right now.

>Win 10 on Virtualbox guest, macOS host.

Any reason why you don't run native?


.

**Comment by btoland** [comment] 2021-09-10 11:43
Hi Jantje,

Thanks for the quick reply.

I was obsessing about putting together a super "clean" bundle with the Sloeber plugin and a some others but I'm going to take your advice and try build off the Sloeber product instead.

I'm using this for teaching embedded programming and as students are mainly on Win10 so I work in a VM.  Also, then students on linux or macos can run on VM too and I only have one platform to support.

In future I might go back and build the plugin from source but just don't have time right now.

Thanks for the great work on this tool - it is excellent.

**Comment by jantje** [comment] 2021-09-10 12:17
> teaching embedded programming

Can you share the school and class? I like to boast from time to time ;-)
Don't hesitate to create specific school situation tickets or share experiences.

**Comment by btoland** [comment] 2021-09-10 13:01
TU Dublin - Ireland.  Computer Engineering Programme.

Thinking about it again now, I realise one of the reasons I'd like the plugin is because I want to introduce Eclipse as our IDE for native C/C++ development when teaching programming before adding Sloeber, AVR plugin etc and moving on to embedded.

There are arguments to keeping separate eclipse instances for different development platforms but it would be nice to have one IDE to rule them all... but maybe separate might be better... I'll keep playing with it...

**Comment by Kilill** [comment] 2021-09-10 14:28
I have tried to reproduce the original error without success, but,  thinking back to what i did i might have an idea, at some point i exterminated any trace of eclipse on the machine, and i think the important directory to get rid of /rename is the C:\Users\<yourUserNameHere>\.eclipse in addition to any install directory. (This will kill of any plugins/extensions etc that you might have previously) Then I did the following dance

1. Install eclipse normally, this will populate the "Software Sites" with the normal suspects:
<img width="448" alt="virgin" src="https://user-images.githubusercontent.com/12996386/132867420-73808055-ef22-4676-95dd-eff6aac92d4a.PNG">

2.  Try to install Sloeber Plugin from marketplace , (Help->Eclipse Marketplace,  Search for Sloeber) this will fail with:
<img width="608" alt="marketPlaceInstall1" src="https://user-images.githubusercontent.com/12996386/132867514-63979c28-404d-4972-bef5-2b3d0c17fa1b.PNG">
3. The "Software List" has now been updated to:
<img width="602" alt="afterInstallHL" src="https://user-images.githubusercontent.com/12996386/132867780-f5d8cdd8-5978-4299-9b5d-39df912e1a18.PNG">
4. Disabled all the new entries  **Except** the Sloeber site
5. Install Sloeber by Help-Install New Software, select the Sloeber site and add the Plugin.
6. It now installed without errors.

**Comment by jantje** [comment] 2021-09-10 14:38
@btoland 
Thanks
Thing is the sloeber product is eclipse + eclipse ide + CDT + sloeber
So even having sloeber installed you can use it as CDT 
Sloeber adds the sloeber toolbar and arduino menu but you can easily remove this from the CDT perspective giving you a plain CDT look.
The only direct visual hints about sloeber (once started) then are the about and the arduino in preferences 
Note that the arduino in new CDT project is from CDT and has nothing to do with Sloeber.

**Comment by jantje** [comment] 2021-09-10 14:52
@Kilill 
Thanks for the research. I'll see whether sloeber specifies these update sites. What I think about them
The CDT9 is bad 
Nebula is probably referenced and apparently no more needed
The eclipse repository should be the way to go.
The embedded C++ is "competition" that has been abandoned and the reference for sure should not be coming from sloeber
Part of GNU MCU is part of the sloeber product but not from the plugin. IMHO this has recently become part of CDT so the update site may no longer be needed for the product

Thinking about this. Are you trying to install the product and not the plugin via marketplace?
Because via marketplace adding a plugin you should add the plugin not the product.
I know it is confusing but marketplace lets you specify whether the install is a product or a plugin so I added both but to add a plugin one should use the plugin not the product.
As should be clear from my update site remarks the product installs other goodies (like the gnu mcu debugger and egit) and that is why we advice to install the product (using the downloadable archive).

**Comment by Kilill** [comment] 2021-09-10 17:04
> Thinking about this. Are you trying to install the product and not the plugin via marketplace?

No its the plugin (background for that: Already have an eclipse installation...)

**Comment by wimjongman** [comment] 2021-09-10 18:34
I am working on this via https://github.com/Sloeber/arduino-eclipse-plugin/issues/1381

**Comment by jantje** [comment] 2021-09-10 22:39
Looking at the update sites from the products
![afbeelding](https://user-images.githubusercontent.com/1175841/132924067-3d7bab3a-4f8d-4be3-a932-95fba90af712.png)
I see a new entry with http://https for which I think @wimjongman should take a look
The update site plugin holds clearly wrong values
![afbeelding](https://user-images.githubusercontent.com/1175841/132924466-c8e4160c-9023-4246-9da8-4fa43a14331e.png)

Based on that and the info @Kilill presented it looks to me that the marketplace adds the update sites of the update plugin to the update sites of the eclipse install before trying to install the plugin.
From previous experiences with update sites and the install functionality it looked as if these update sites mentioned in the update site plugin were not used (and therefore neglected)

**Comment by jantje** [comment] 2021-09-10 22:40
pressed the wrong button

**Comment by jantje** [comment] 2021-09-10 23:07
Done some more checking
Gnu mcu definitely moved to CDT. I need to check if the package name is still valid or has changed in the transition. But the update site is no longer needed.
The nebula update site is needed

**Comment by btoland** [comment] 2021-09-13 10:13
@Kilill 
> Then I did the following dance

Thanks @Kilill.  That dance worked perfectly for me.  Didn't have to delete the .eclipse directory - just disabled the sites after the marketplace install and then installed as New Software.

**Comment by btoland** [comment] 2021-09-13 11:35
Got excited and spoke too soon!
Getting the following after that dance on eclipse restart...
Getting same when just trying to install plugin as New Software (no Marketplace attempt) on a fresh eclipse (deleted the.eclipse folder in user home folder too).

![Capture](https://user-images.githubusercontent.com/23100955/133071786-61084441-b423-4ec2-b2b2-35d3ffca3b7d.PNG)

This is what my vanilla eclipse update site looks like:
![update sites pre sloeber](https://user-images.githubusercontent.com/23100955/133075535-b9ce8a26-62cf-4149-8184-296e4f6b130b.PNG)

This is it post Sloeber plugin install from marketplace:
![update sites post sloeber](https://user-images.githubusercontent.com/23100955/133075611-1561cd5d-20a0-41ae-80e7-6e32f3ee614b.PNG)

When I disable all the new sites as suggested by @Kilill I get the below: - guess some dependency unresolved.
![error after disabling update sites except sloeber](https://user-images.githubusercontent.com/23100955/133076479-16bb891d-06b3-46b1-9e2a-5a21553bbd7d.PNG)

![error log after disabling updates sites except sloeber](https://user-images.githubusercontent.com/23100955/133076500-46c6624a-8b65-4bac-bd27-ecb90b06fe25.PNG)


Continuing with using product as base but would still like option to walk students through from a vanilla Eclipse install.

**Comment by jantje** [comment] 2021-09-13 12:50
@btoland 
Sloeber is clearly installed as the error message "failed to parse..." is an error message from sloeber.
So indeed probably a dependency problem but to no longer a update problem.
For the dependency problem I would like to have the stack trace that should be visible in details or the log.

In the mean time  did some changes to the update site and @wimjongman made the github builds available so could you download the repository (=zipped update site) of the latest build here https://github.com/Sloeber/arduino-eclipse-plugin/actions/runs/1224353006
Unzip the repository 
point to it in update sites 
deactivate the baeyens.it update sites
And try to add sloeber to a eclipse install from the local repository

Note that the safest way for teaching is to have a specific download zip and update repository on your local network as this minimise"s external dependencies.

If this works I think I'll release 4.1.1

**Comment by btoland** [comment] 2021-09-13 13:27
Hi @jantje,

Tried the local repository install but getting similar issues - details below:

![new repository install error](https://user-images.githubusercontent.com/23100955/133091190-620fe89a-d8ec-43d6-9d31-1862ef3523a1.PNG)

![new repository update sites](https://user-images.githubusercontent.com/23100955/133091219-4136c160-abe1-4ec5-8494-123fcf9c4adb.PNG)

Is this the stack trace you requested?  It's the logfile from that last attempt to install the plugin from the local repository.
[.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/7154567/default.log)

On teaching, yes I agree the safest/easiest/least painful is to provide a specific download which is what I'm working on.  However, part of teaching is to prep them for the real world so a bit of exposure to tool configuration will stand them well - always a balancing act!

**Comment by jantje** [comment] 2021-09-13 14:59
It is really strange the nebula stuff is not found.
When I check the nebula update site on my system I see the versions That can not be installed on you system.
![afbeelding](https://user-images.githubusercontent.com/1175841/133107407-6fe32699-931a-4907-aacf-d48a0946811c.png)

Was the nebula there before you tried?
Can you try again?

**Comment by wimjongman** [comment] 2021-09-13 15:07
@btoland please press CTRL+3 -> Copy configuration data to clipboard -> paste to file -> attach

**Comment by btoland** [comment] 2021-09-13 15:23
@jantje 

Nebula site not in list before trying to install plugin:
![update sites vanilla CDT](https://user-images.githubusercontent.com/23100955/133111566-ab1a35f2-6c25-45d2-b471-d326ae46e148.PNG)

Then after:
![new repository update sites](https://user-images.githubusercontent.com/23100955/133111646-54596e6f-c687-4329-87a6-da4039d37125.PNG)

**Comment by btoland** [comment] 2021-09-13 15:24
@wimjongman 

Config data:
[config data.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/7155449/config.data.txt)

**Comment by jantje** [comment] 2021-09-13 15:25
I can reproduce the issue.

Download the repository (and unzipped it)
Download the eclipse java https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-06/R/eclipse-java-2021-06-R-win32-x86_64.zip
Start eclipse java
Add the repository to the update sites
![afbeelding](https://user-images.githubusercontent.com/1175841/133111925-aeaef18f-ba5a-4613-bc5a-1b9c16fd5619.png)

Try to add sloeber plugin

![afbeelding](https://user-images.githubusercontent.com/1175841/133111764-8e74b913-cf09-44b7-954f-67c0d50abc75.png)

**Comment by jantje** [comment] 2021-09-13 15:28
So I tried to install nebula
![afbeelding](https://user-images.githubusercontent.com/1175841/133112279-ee231e3f-8898-4fd1-84b4-6fcd30ccda30.png)
Will start from fresh to do a nebula install

**Comment by jantje** [comment] 2021-09-13 15:40
installing nebula in a fresh java ide worked
![afbeelding](https://user-images.githubusercontent.com/1175841/133114250-e40b4939-6518-4c6b-bdca-2baa3eb31e4b.png)

**Comment by btoland** [comment] 2021-09-13 15:46
@jantje 
I went that route too when I initially hit this.  Nebula install went fine on vanilla CDT but then ran into bunch of probs when I tried installing Sloeber afterwards.  Haven't tried with local repository version yet.

**Comment by jantje** [comment] 2021-09-13 16:22
I could install sloeber after nebula install and then ran into the "failed to parse json" problem.
Seems something is missing

**Comment by jantje** [comment] 2021-09-13 18:37
I did some more testing and I though I knew what was happening and then ... it started working :-(

Here is my reasoning (all tests have done starting from a fresh java eclipse download mentioned above)
1) If I succeed in installing nebula in eclipse I can install sloeber without problems
2) To install nebula I need to add https://download.eclipse.org/releases/latest/ to the update sites or it fails to install.
3) with only the update sites https://download.eclipse.org/releases/latest/ and https://download.eclipse.org/nebula/releases/latest/ I can install nebula and then add Sloeber from the repository

![afbeelding](https://user-images.githubusercontent.com/1175841/133135508-1666b933-b512-4648-bb0e-a94fe2a20c84.png)
![afbeelding](https://user-images.githubusercontent.com/1175841/133135570-6122c566-994a-4719-8bbb-95f06c22872f.png)
![afbeelding](https://user-images.githubusercontent.com/1175841/133135713-e6a810c9-11c6-4699-8217-bb51b1717926.png)
So this tells me nebula does not reference all update sites needed
Adding https://download.eclipse.org/releases/latest/ too the update sites and nebula installs
![afbeelding](https://user-images.githubusercontent.com/1175841/133136147-280ee7fe-ecc9-4cf4-9041-256560b545fc.png)
Then adding the repository mentioned above I can install Sloeber (I did not even restart eclipse)
![afbeelding](https://user-images.githubusercontent.com/1175841/133136682-2f8897a9-667b-4dc9-a106-eb67b04c63b4.png)
And after restart I get the error related to java 16
![afbeelding](https://user-images.githubusercontent.com/1175841/133136878-52a2fd15-ec18-461f-8760-e2a133213e8a.png)
And I end up with these update sites (which contains nothing alarming to me)
![afbeelding](https://user-images.githubusercontent.com/1175841/133137205-9516ef9c-1136-4513-8e3f-bb2f26bef04b.png)

Deleting eclipse install and starting over
Setting the update sites to
![afbeelding](https://user-images.githubusercontent.com/1175841/133137954-c544964b-74b4-43ca-8f59-edf9ec29ce75.png)
And trying to install Sloeber
![afbeelding](https://user-images.githubusercontent.com/1175841/133138335-bc13168b-2388-4ca3-b061-234b56de5884.png)
Seems to work

**Comment by jantje** [comment] 2021-09-13 18:57
I think I get it now
To install sloeber one needs to add the sloeber repository and the nebula repository and then all works fine.
However when you tried to install sloeber without having the nebula repository you need to restart for it to work.
I think the need for the nebula repository to be in the update site is because nebula does not reference the https://download.eclipse.org/releases/latest/ update site (which it should)

@wimjongman can you try to add https://download.eclipse.org/releases/latest/ to the category.xml of the update site of nebula?
Note that you have to add it to the text editor or an extra http:// will be added.

**Comment by wimjongman** [comment] 2021-09-14 14:28
The default update sites for any stock Eclipse installation are:

* Eclipse Simultaneous Release - https://download.eclipse.org/releases/xx.xx
* The Eclipse Project Updates - http://download.eclipse.org/eclipse/updates/xx.xx

These should be also part of the Sloeber product, together with any other update sites.

**Comment by wimjongman** [comment] 2021-09-14 14:33
> However when you tried to install Sloeber without having the nebula repository you need to restart eclipse for it to work.

Sometimes you need to restart...
sometimes not...
sometimes you need to restart more than once... 
or first, remove the nebula repository and then select Sloeber again...

This is not consistent behavior therefore, I think this is an Eclipse issue.

**Comment by jantje** [comment] 2021-09-14 20:49
> 
> 
> > However when you tried to install Sloeber without having the nebula repository you need to restart eclipse for it to work.
> 
> Sometimes you need to restart...
> sometimes not...
> sometimes you need to restart more than once...
> or first, remove the nebula repository and then select Sloeber again...
> 
> This is not consistent behavior therefore, I think this is an Eclipse issue.

What I mean is: once it failed with the error message during install, eclipse only recovers after restarting.

**Comment by wimjongman** [comment] 2021-09-14 21:13
> What I mean is: once it failed with the error message during install, eclipse only recovers after restarting.

 Not always.

**Comment by jantje** [comment] 2021-09-14 21:17
Well it never did in this test case during these tests

**Comment by jantje** [comment] 2021-09-15 00:22
> 
> 
> The default update sites for any stock Eclipse installation are:
> 
>     * Eclipse Simultaneous Release - https://download.eclipse.org/releases/xx.xx
> 
>     * The Eclipse Project Updates - http://download.eclipse.org/eclipse/updates/xx.xx
> 
> 
> These should be also part of the Sloeber product, together with any other update sites.

If I understand correctly you say the sloeber update site should reference these update sites (which it does) and so should nebula (which it doesn't; I checked; tried to add it; everything became complex)

**Comment by wimjongman** [comment] 2021-09-15 07:50
The Sloeber **update site** should only add update sites that are not expected to be available. So it is not needed to add the two Eclipse Repos. It should add Nebula because that is not expected to be there.

Nebula should not add the two Eclipse repos because they are expected to be there.

**Our product** should add all repos because no one else adds them.

**Comment by wimjongman** [comment] 2021-09-15 07:52
I am currently debugging P2 but it is a big confusing log. I don't understand why it tries to add the CDateTime widget because we don't use that.

We should try to install only CDT and see if that one fails to install as well.

**Comment by jantje** [comment] 2021-09-15 11:14
First of all thanks for the update on what is expected in the update sites.
I think debugging P2 is the way to go but I also think it is a long lasting problem and as such probably hard to find.
My guess from the behaviour I see is that the install exists out of 2 main steps. Step 1 is "Validation of the installability of the selected components" (enables finish) and step 2 "actual install of the components".
It looks to me as if the list of update sites used in these 2 steps are different.
I say so because I remember testing a sloeber update site without the nebula update site and I got "Can not install nebula" error message in step 1.

>We should try to install only CDT and see if that one fails to install as well.

Isn't that what we are doing when installing nebula first and then add Sloeber? That works fine.

**Comment by jantje** [comment] 2021-09-15 11:42
> We should try to install only CDT and see if that one fails to install as well.

Thinking about this. I tried this test (which failed in the past)
Install nebula
![afbeelding](https://user-images.githubusercontent.com/1175841/133424779-d7fdc092-d0e1-454e-93d7-541b65cc3257.png)
Installs fine; restart eclipse
Remove all update sites and add sloeber update site.
This puts CDT in the situation it needs to be installed based on a update site only referenced in the sloeber update site
![afbeelding](https://user-images.githubusercontent.com/1175841/133425090-81bfe356-5937-4b6f-9cbd-916bd024abaa.png)
Step 2 fails
![afbeelding](https://user-images.githubusercontent.com/1175841/133425535-1925a11e-405a-48fa-b0c0-31dd8e05bdcc.png)
I restarted eclipse (just to flush all install caches)
As you can see the update sites do not contain http://download.eclipse.org/eclipse/updates/xx.xx 
![afbeelding](https://user-images.githubusercontent.com/1175841/133426041-3498ff1a-27af-46a8-8ed9-dbab5d64c2db.png)

remove all but sloeber and add http://download.eclipse.org/eclipse/updates/latest
![afbeelding](https://user-images.githubusercontent.com/1175841/133426363-59e2221a-3c40-4471-afae-e058e7ca3fcf.png)

and I get the same error
![afbeelding](https://user-images.githubusercontent.com/1175841/133426447-c983989a-39b7-4398-ba37-caf2f37b0163.png)

without editing the update stites
tried again same error
restarted and tried again 
installed

From this I conclude that installation step 2 does not take all the update sites into account gathered in step 1

**Comment by jantje** [comment] 2021-09-15 11:58
And I also have the feeling it is the caching that doesn't update as it should. 
If one can flush the caches easily; I would add a cache flush when pressing finish. That should answer the question "is this a cache issue or not"

**Comment by wimjongman** [comment] 2021-09-15 12:38
I already tried that. You can go to the preferences and "Reload" every update site but it does not work either.

**Comment by jantje** [comment] 2021-09-15 14:00
Good now we know it is not only a caching issue 🥇 (or there are more caches than we know of )
Next thing I would try is dumping/validating the update sites searched for at the time of failing to find.

Mental note to myself: As this should never happen -due to step 1 validation- this may be an ignored exception

**Comment by btoland** [comment] 2021-09-21 09:45
Finally got the plugin to install on vanilla eclipse 2021-06/2021-09 CDT.  Windows 10.  No JRE installed.

The workarounds listed at the top of this thread did not work for me but gave me a hunch so tried below which worked for me:

1. Started with eclipse CDT 2021-06 download as per CDT download site.  All previous eclipse folders, workspaces etc deleted so fresh install.
2. Before running the "Check for Updates" to update CDT - manually added to "Available Software Sites":
    https://download.eclipse.org/nebula/releases/latest/
    http://eclipse.baeyens.it/update/V4/stable
3. Ran Check for Updates to update CDT/Eclipse and did restart requested. (perhaps this sorted out the various caching issues mentioned above??).
4. After update installed Sloeber by using Help->Install New Software and selecting Sloeber update site.
5. Sloeber installed and eclipse restarted.
6. Then ran into the JRE16 issue with "Cannot parse..." as using the bundled JRE that now comes with eclipse.
7. Added the " --illegal-access=permit" (#1339, #1384 workaround) line to the END of my eclipse.ini (didn't work after -vm line) and restarted.
8. All good. Happy Days.

**Comment by wimjongman** [comment] 2022-01-02 10:15
I think this is fixed with: https://github.com/Sloeber/arduino-eclipse-plugin/pull/1431

**Comment by rtek1000** [comment] 2022-06-05 18:47
I believe I had this problem too, with the current version IDE: Version: 2022-03 (4.23.0)

**Comment by jantje** [comment] 2022-06-05 19:43
@rtek1000 I think upgrading will always have it's difficulties.

**Comment by CelimoC** [comment] 2022-11-11 13:21
to install Arduino sloeber in Eclipse IDE.

1) there is an error when installing from the market place

An error occurred while collecting items to be installed
session context was:(profile=C__Users_dcela_cpp-2022-092_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.nebula.widgets.oscilloscope,1.4.0.202208171909
No repository found containing: org.eclipse.update.feature,org.eclipse.nebula.widgets.oscilloscope.feature,1.4.0.202208171909
No repository found containing: osgi.bundle,org.eclipse.nebula.widgets.oscilloscope.source,1.4.0.202208171909
No repository found containing: osgi.bundle,org.hamcrest.core,1.3.0.v20180420-1519
No repository found containing: osgi.bundle,org.junit,4.13.2.v20211018-1956

2) solution
Help->Install new update-> Add
copy paste in Location: https://download.eclipse.org/nebula/releases/latest/
in work with : io.sloeber.updatesite - http://eclipse.baeyens.it/update/V4/stable

Select all and install.
then Sloeber should be installed. it is not needed market place



got this error, but not paying attention:

Due to issues with long pathnames on Windows, the Sloeber installation path must be less than 40 characters. 
Your current path: C:/Users/dcela/cpp-2022-092/eclipse/arduinoPlugin is too long and the plugin will no longer function correctly for all boards.
Please visit issue #705 for details. https://github.com/Sloeber/arduino-eclipse-plugin/issues/705
Alternatively use the environment var SLOEBER_HOME.

Sloeber might still function but if you get strange results you know where to look.
Do not reate an issue if you see this!!!

cheers
/Celimo

**Comment by dlarue** [comment] 2023-03-13 16:12
Still and issue after installing Eclipse 2022-12 CDT,  needed to manually install Nebula using the Help->Install New Software option adding http://download.eclipse.org/nebula/releases/latest/ repository and installing Nebula packages.

After Eclipse restart I could then use the Eclipse Marketplace to install the Arduino plugin.

But I did notice it was using Arduino IDE v 1.8.x packages, compiler and tools and that is deprecated for the Arduino IDE v 2.x.x packages, compiler and build tools.

**Comment by littlegreenrock** [comment] 2023-04-03 05:05
Sloeber plugin for fresh Eclipse install still no bueno after painfully following every bit of advice.

**Closed** 2024-02-20 20:46 UTC
Labels: OS: all, status: workaround documented, domain: configuration, Hot issue
