### ISSUE TITLE
Updating Sloeber to 4.3.1.201810101819 fails because of Nebula version

### ISSUE THREAD

**Issue by Bascy** [Sloeber/arduino-eclipse-plugin#1036] opened 2018-11-10 19:39 UTC
When updating sloeber through "Check updates" in Eclipse the following error occurs, stating that my installed version of Nebula is 1.4.0.2018061814 and Sloeber want 1.4.0.201804281520 (see below for full error message). I've downloaded this Eclipse from sloeber, including all dependencies I think.
How can I solve this?

According to the the Nebula site (https://www.eclipse.org/nebula/downloads.php) there already is a version 2.0.1 by the way

> Cannot complete the install because of a conflicting dependency.
  Software being installed: Sloeber, the Eclipse Arduino IDE (plugin version) 4.3.1.201810101819 (io.sloeber.feature.feature.group 4.3.1.201810101819)
  Software currently installed: Nebula Oscilloscope Widget 1.4.0.201808061814 (org.eclipse.nebula.widgets.oscilloscope.feature.feature.group 1.4.0.201808061814)
  Only one of the following can be installed at once: 
    Nebula Oscilloscope Widget 1.4.0.201808061814 (org.eclipse.nebula.widgets.oscilloscope.feature.feature.jar 1.4.0.201808061814)
    Nebula Oscilloscope Widget 1.4.0.201804281520 (org.eclipse.nebula.widgets.oscilloscope.feature.feature.jar 1.4.0.201804281520)

**Comment by jantje** [comment] 2018-11-10 19:50
If I remember correctly deinstalling nebula before upgrading worked fine.

**Comment by Bascy** [comment] 2018-11-10 20:01
That did the trick

**Comment by wimjongman** [comment] 2018-11-14 11:21
This is caused by the fact that the Nebula plugin is included and not referenced. I will take a look.

**Comment by wimjongman** [comment] 2018-11-14 11:33
Fixed with commit 090072ce82e7a9cafc126dfde6a037e91ee1ceab

**Closed by wimjongman** 2018-11-14 11:33 UTC
Labels: domain: releng
