### ISSUE TITLE
V4.2 ESP8266 upload speed is always 19200

### ISSUE THREAD

**Issue by eXtatic-GitHub** [Sloeber/arduino-eclipse-plugin#913] opened 2018-02-01 15:48 UTC
Hey guys,

hopefully just a minor issue here.
Coming from V4.1 I wondered why flashing took so much time after updating to 4.2.
I figured out that the esptool.exe is always started with parameter -cb 19200, eventhough the upload speed is configured to 115200 (or any other value).

Probably related environment variable:
A.UPLOAD.SPEED is automatically set to 19200 upon build
![image](https://user-images.githubusercontent.com/5675570/35687556-5b7efd36-076f-11e8-8b3b-6a7aefafe56a.png)

JANTJE.MENU.UPLOADSPEED shows the configured value, in my case 115200.UPLOAD.SPEED
![image](https://user-images.githubusercontent.com/5675570/35687530-4e57be9a-076f-11e8-968f-24672eb4a5ac.png)

![image](https://user-images.githubusercontent.com/5675570/35687580-6a3ee642-076f-11e8-9b0c-4d8630928957.png)

**Comment by jantje** [comment] 2018-02-02 15:11
seems a duplicate of #907

**Closed** 2018-02-02 16:18 UTC
Labels: status: duplicate
