### ISSUE TITLE
Cannot select Arduino boards in preferences (4.3.3)

### ISSUE THREAD

**Issue by grijspetje** [Sloeber/arduino-eclipse-plugin#1248] opened 2020-11-06 08:19 UTC
Hi all,

I searched for a solution but couldn't found any. I followed the installation procedure on the site and tried the suggestion as mentioned in issue 1196:

"Read speedfixer's comment towards the bottom. His workaround worked for me. Clearer instructions are "Click Arduino in menu bar and select preferences. In the Preferences window, under Arduino, click Platforms and Boards. Drill down through arduino, Then Arduino AVR boards and then select the version" "Apply and Close". Wait for the activity in the bottom right-hand corner to die down. Close and re-open Eclipse and your problem has gone away."

My preference pane shows all the boards but I cannot select them. So the initial problem I started with (cannot down load boards from dowloads.arduino.cc ...) still remains. Please help me out!

Thanks,

Kind regards,

Peter

**Comment by jantje** [comment] 2020-11-06 20:25
please sharesome screenshots
the boardsmanager installed boards for instance and the new project wizard board selection

**Comment by grijspetje** [comment] 2020-11-07 18:00
Here are three screen shots:

The first I see is the "Problem occurred after startup" and the corresponding error log screenshot "Error log after startup" 

And then the screenshot of the window in which I cannot make any selections: "No selections Arduino Preferences"

Thanks for the help

**Comment by grijspetje** [comment] 2020-11-07 18:03
![Error log after startup](https://user-images.githubusercontent.com/44427716/98448374-dcffe400-212b-11eb-9d32-4e2159ba2941.png)
![No selection Arduino Preferences](https://user-images.githubusercontent.com/44427716/98448379-e2f5c500-212b-11eb-9fba-8722327ac567.png)
![Problem occured after startup](https://user-images.githubusercontent.com/44427716/98448380-e2f5c500-212b-11eb-8a2c-f523e93245ab.png)

**Comment by jantje** [comment] 2020-11-07 18:43
you did not do the workaround yet.
You have to click on one of the trangles to see the available versions and then select one of the versions
![afbeelding](https://user-images.githubusercontent.com/1175841/98449149-7382d400-2131-11eb-96dd-0054415aa35b.png)

**Comment by jantje** [comment] 2020-11-08 12:40
duplicate of #1245

**Closed by jantje** 2020-11-08 12:40 UTC
Labels: status: duplicate
