### ISSUE TITLE
buil stm8 error use official core

### ISSUE THREAD

**Issue by WangChun420** [Sloeber/arduino-eclipse-plugin#1421] opened 2021-12-13 02:46 UTC
when build,it cant output xxx.o,is ther some bug in platform.slober
'Starting archiver'
"D:\Sloeber\arduinoPlugin\packages\STMicroelectronics\tools\cxppstm8\4.1.3\clib.exe" -e -r -p     C:\Users\Auto\Documents\sloeber-workspace\example\Release/arduino.ar  .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_adc.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_aes.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_awu.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_beep.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_can.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_clk.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_comp.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_dac.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_dma.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_exti.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_flash.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_gpio.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_i2c.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_irtim.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_itc.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_iwdg.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_lcd.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_pwr.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_rst.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_rtc.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_spi.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_syscfg.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim1.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim2.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim3.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim4.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim5.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim6.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart1.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart2.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart3.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart4.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_usart.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_wfe.c.o .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_wwdg.c.o  .\core\core\stm8\PinConfigured.c.o .\core\core\stm8\PortNames.c.o .\core\core\stm8\analog.c.o .\core\core\stm8\clock.c.o .\core\core\stm8\digital_io.c.o .\core\core\stm8\hw_config.c.o .\core\core\stm8\interrupt.c.o .\core\core\stm8\pinmap.c.o .\core\core\stm8\spi_com.c.o .\core\core\stm8\stm8_def.c.o .\core\core\stm8\stm8_eeprom.c.o .\core\core\stm8\stm8_it.c.o .\core\core\stm8\timer.c.o .\core\core\stm8\twi.c.o .\core\core\stm8\uart.c.o  .\core\core\avr\dtostrf.c.o  .\core\core\HardwareSerial.cpp.o .\core\core\IPAddress.cpp.o .\core\core\Print.cpp.o .\core\core\RingBuffer.cpp.o .\core\core\Stream.cpp.o .\core\core\Tone.cpp.o .\core\core\WInterrupts.c.o .\core\core\WMath.cpp.o .\core\core\WString.cpp.o .\core\core\abi.cpp.o .\core\core\board.c.o .\core\core\hooks.c.o .\core\core\itoa.c.o .\core\core\main.cpp.o .\core\core\new.cpp.o .\core\core\pins_arduino.c.o .\core\core\syscalls_stm8.c.o .\core\core\wiring_analog.c.o .\core\core\wiring_digital.c.o .\core\core\wiring_pulse.cpp.o .\core\core\wiring_shift.c.o .\core\core\wiring_time.c.o 
can't open .\core\core\HardwareSerial.cpp.o
can't open .\core\core\IPAddress.cpp.o
can't open .\core\core\Print.cpp.o
can't open .\core\core\RingBuffer.cpp.o
can't open .\core\core\Stream.cpp.o
can't open .\core\core\Tone.cpp.o
can't open .\core\core\WInterrupts.c.o
can't open .\core\core\WMath.cpp.o
can't open .\core\core\WString.cpp.o
can't open .\core\core\abi.cpp.o
can't open .\core\core\avr\dtostrf.c.o
can't open .\core\core\board.c.o
can't open .\core\core\hooks.c.o
can't open .\core\core\itoa.c.o
can't open .\core\core\main.cpp.o
can't open .\core\core\new.cpp.o
can't open .\core\core\pins_arduino.c.o
can't open .\core\core\stm8\PinConfigured.c.o
can't open .\core\core\stm8\PortNames.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_adc.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_aes.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_awu.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_beep.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_can.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_clk.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_comp.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_dac.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_dma.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_exti.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_flash.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_gpio.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_i2c.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_irtim.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_itc.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_iwdg.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_lcd.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_pwr.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_rst.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_rtc.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_spi.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_syscfg.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim1.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim2.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim3.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim4.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim5.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_tim6.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart1.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart2.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart3.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_uart4.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_usart.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_wfe.c.o
can't open .\core\core\stm8\STM8_StdPeriph_Driver\stm8xx_wwdg.c.o
can't open .\core\core\stm8\analog.c.o
can't open .\core\core\stm8\clock.c.o
can't open .\core\core\stm8\digital_io.c.o
can't open .\core\core\stm8\hw_config.c.o
can't open .\core\core\stm8\interrupt.c.o
can't open .\core\core\stm8\pinmap.c.o
can't open .\core\core\stm8\spi_com.c.o
can't open .\core\core\stm8\stm8_def.c.o
can't open .\core\core\stm8\stm8_eeprom.c.o
can't open .\core\core\stm8\stm8_it.c.o
can't open .\core\core\stm8\timer.c.o
can't open .\core\core\stm8\twi.c.o
can't open .\core\core\stm8\uart.c.o
can't open .\core\core\syscalls_stm8.c.o
can't open .\core\core\wiring_analog.c.o
can't open .\core\core\wiring_digital.c.o
can't open .\core\core\wiring_pulse.cpp.o
can't open .\core\core\wiring_shift.c.o
can't open .\core\core\wiring_time.c.o
make: *** [makefile:78: C:\Users\Auto\Documents\sloeber-workspace\example\Release\arduino.ar] Error 1
"D:/Sloeber/arduinoPlugin/tools/make/make all" terminated with exit code 2. Build might be incomplete.

**Comment by jantje** [comment] 2021-12-13 13:29
This is a duplicate of #1287

**Closed by jantje** 2021-12-13 13:29 UTC
Labels: status: duplicate
