### ISSUE TITLE
Unable to complete installation of 4.4.1 Product on Linux Mint

### ISSUE THREAD

**Issue by martin-12345** [Sloeber/arduino-eclipse-plugin#1559] opened 2023-04-01 10:03 UTC
Do you use the Sloeber product or plugin?    **Product**
Sloeber version number  **4.4.1**
OS:**Linux Mint**
The url of the json that you used to download the platform  **http://eclipse.baeyens.it/stable.php?OS=Linux**
A image of the project properties arduino showing the board settings   

**Describe the bug**   
After launching sloeber-ide, choosing my workspace etc it tells me it's finishing the installation. Fails with 

"Failed to install Arduino AVR Boards
Failed to extract tar.bz2. "/home/martin/Sloeber/arduinoPlugin/downloads/avr-1.8.6.tar.bz2".
Cannot run program "chmod": error=13, Permission denied"

Log is
 
![image](https://user-images.githubusercontent.com/59409509/229279621-234d9a96-ff4d-4f95-9164-f39438884dce.png)

**Comment by jantje** [comment] 2023-04-01 16:23
this looks like a duplicate of #1557

**Closed** 2024-02-20 17:04 UTC
