### ISSUE TITLE
Program "\bin\g++" not found in PATH, Program "\bin\gcc" not found in PATH  

### ISSUE THREAD

**Issue by Danial-Zafar** [Sloeber/arduino-eclipse-plugin#869] opened 2017-11-21 11:08 UTC
Issue while using v 4.1 on win64: When I switch from release to local(which is a debug project), it started to disappear some things from Include folder and give above mentioned 2 error

![0](https://user-images.githubusercontent.com/16437575/33069064-1a07ad80-ced5-11e7-8ed2-0e87948b6ffd.png)
![1](https://user-images.githubusercontent.com/16437575/33069065-1a425eee-ced5-11e7-80e4-338047ca201d.png)
![2](https://user-images.githubusercontent.com/16437575/33069067-1a786386-ced5-11e7-88d0-428f2bdf8ea4.png)
![3](https://user-images.githubusercontent.com/16437575/33069068-1aa981be-ced5-11e7-8fcd-4550f0178661.png)
![4](https://user-images.githubusercontent.com/16437575/33069069-1adde6ca-ced5-11e7-9cce-16c43e039c89.png)
![5](https://user-images.githubusercontent.com/16437575/33069070-1b0ea030-ced5-11e7-9a19-f901d5e99a12.png)

**Comment by Danial-Zafar** [comment] 2017-11-21 11:15
when I build this in this state it showed an error of 
subdir.mk.24: recipe for target 'ino.cpp.o' failed
make: *** [.ino.cpp.o] Error1

I tried on of your solution that is mentioned one of issues which to add cmd.exe/c in build command

**Comment by jantje** [comment] 2017-11-21 13:45
duplicate of #867

**Closed by jantje** 2017-11-21 13:45 UTC

**Comment by wimjongman** [comment] 2017-11-21 13:49
#870

**Comment by jml3on** [comment] 2018-08-10 15:53
HI,

running into this issue as well.
If I run through the clean cycle from the debug video (install mingw in a folder with no space; run sloeber.cmd; create blink project; install hardware from git; create debug config; build), I invevitably get:

08:48:57 **** Incremental Build of configuration Debug for project blink ****
"C:\\sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ..\sloeber.ino.cpp'
'Starting C++ compile'
"/bin/g++" -c -g -O0 -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR_LOCAL   -DLOCAL_RUN   -I"C:\github\hardware\jantje\avr_local\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard" -MMD -MP -MF"sloeber.ino.cpp.d" -MT"sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "..\sloeber.ino.cpp"  -o  "sloeber.ino.cpp.o"   -Dsrandom=srand -Drandom=rand
The system cannot find the path specified.
subdir.mk:18: recipe for target 'sloeber.ino.cpp.o' failed
make: *** [sloeber.ino.cpp.o] Error 1

08:48:58 Build Failed. 2 errors, 0 warnings. (took 248ms)


I've tracked it down to the environment variable A.RUNTIME.TOOLS.MINGW.PATH not being set.

If I set it manually in my config, the build works. But after a while (not sure what triggers it), that variable disappears and the problem comes back.

So far, I haven't been able to figure out how those environment variables are generated nor from where.

Pointer would be greatly apreciated.

**Comment by jml3on** [comment] 2018-08-11 05:12
to clarify for others who may get stuck like I did: manually installing jantje/hardware is no longer required since sloeber 4.2 (and will lead to that broken experience).

debug platforms are now bundled and only need to be selected under Arduino > Preferences > Platforms and Boards.

**Comment by jantje** [comment] 2018-08-11 12:02
>So far, I haven't been able to figure out how those environment variables are generated nor from where.

A very old post (by now incomplete) but still very valid
http://blog.baeyens.it/#post24
