### ISSUE TITLE
Sloeber - STM32Bluepill - fail to call STM32Cube to download target

### ISSUE THREAD

**Issue by SigP226** [Sloeber/arduino-eclipse-plugin#1462] opened 2022-04-08 18:54 UTC
Hello,

ENVIRONMENT: 
- Windows 10 / Eclipse 3-22 / CDT / sloeber 4.4 / STM32 v2.2.0 /dark theme / JDK18
- STM32 Bluepill connected via STLINK V2 
Preliminary test to disciminate the issue: 
- JDK16 or 18 same problem, Was in 16, I upgrade to 18 to see if it was java version the root cause
- Code compilation OK, no errors nor warnings despite this bizarre error in the LOG : 
![image](https://user-images.githubusercontent.com/26750209/162500400-1ae2f7a0-bfe3-4942-8d54-206d4e435eff.png)
- To check the STLINK link, I have used STM32cube (graphical version, not the command line) and I can download the HEX file without any issue and code works well. So the issue is not coming from the connection between the board, the STLINK and the PC.
- test on full new empty project (LED blink). Same result

ISSUE DESCRIPTION 

After code compilation, when I push the download button the system fail to launch the downloder (STM32cube)
I get this error:
![image](https://user-images.githubusercontent.com/26750209/162499684-19d22947-e884-4c6d-9bb5-7b7928f0b4ce.png)
and this error
![image](https://user-images.githubusercontent.com/26750209/162499937-f22e1ae2-cd6e-4ab2-abd8-0ecb0aa9bb05.png)

I have check the "stm32CubeProg.sh" file and eveything seems ok. Seems the parameter sent to the SH file are wrong somwhere.

any idea?

**Comment by jantje** [comment] 2022-04-08 20:20
Can you provide the output from the upload console?

**Comment by SigP226** [comment] 2022-04-09 06:10
Here is

![image](https://user-images.githubusercontent.com/26750209/162559120-e3954a8f-14d7-4abc-8333-ba71e50233da.png)

**Comment by jantje** [comment] 2022-04-09 15:09
If I understand correctly you want to use a programmer STM32Cube to upload
If so this may be a duplicate of #1362

**Comment by SigP226** [comment] 2022-04-09 17:44
Yes, I use STM32cube. What cause me trouble is that it was perfectly OK before, that's not the first time I use STLINK system and sloeber/eclipse and it was working fine. I am not sure it is a duplicate of #1362 because I have no issue with arduino. It works fine. The main difference with before is the switch to 2.2.0 of STM32duino.
I dont know very well how it work, I understand the upload command line is created via a pattern in Platform_sloeber.txt : tools.stm32CubeProg.upload.pattern="${busybox}" sh "${tools.stm32CubeProg.path}/${tools.stm32CubeProg.cmd}" ${upload.protocol} "${build.path}/${build.project_name}.bin" ${upload.options}
the command line written in the upload console is correct, the file are at the good location.
I continue to search how it works, but I think the issue is between the creation of command line and the call to the shell macro stm32CubeProg.sh.

**Comment by SigP226** [comment] 2022-04-09 18:37
root cause found! I think the issue is in plateform_sloeber.txt 
![image](https://user-images.githubusercontent.com/26750209/162586861-fef346cf-48dc-46b8-b000-126d66432eeb.png)

the pattern does not contain the right path for busybox : 
![image](https://user-images.githubusercontent.com/26750209/162586777-f029c8ac-708e-4811-a0a8-842ff8fd98b8.png)

The upload pattern ask to "busybox" path, but this variable is never declared as we can see in the environment of the project.

![image](https://user-images.githubusercontent.com/26750209/162586582-713d338a-5305-4934-b3f7-5cc126008ca1.png)

![image](https://user-images.githubusercontent.com/26750209/162586503-66bf61fd-df31-4903-b814-1d0f4435730e.png)
So I have manually corrected the environment like this : 

![image](https://user-images.githubusercontent.com/26750209/162587032-99327ee9-35b1-4c00-b9be-92441a113363.png)
 and... magic !!!

![image](https://user-images.githubusercontent.com/26750209/162587041-4ac1c0ab-aa7f-41ba-9729-362f4e480901.png)

I don't know how works Sloeber, I think if I modify manually the platform_sloeber.txt, it will take effect for each new project creation.
I thank you for this very useful tool, I like sloeber, with eclipse it is a dream compare to the arduino IDE.

**Comment by jantje** [comment] 2022-05-30 20:17
closing as duplicate of #1362

**Closed by jantje** 2022-05-30 20:17 UTC
