### ISSUE TITLE
Linker/Combiner problem on fresh install: "cannot find -llwip_src" 

### ISSUE THREAD

**Issue by Gerry33** [Sloeber/arduino-eclipse-plugin#961] opened 2018-04-13 16:18 UTC
Hi all, 
I've an issue with a fresh install of Sloeber 4.2 and a fresh workspace using ESP SDK2.4.1 (ESP SDK2.4.**0** does not have this issue) 

Installation done, all path issues solved. 

Created  a blink project, compile no problem, but the 'combiner' throws this error 
 " ... /4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: **cannot find -llwip_src**
collect2.exe: error: ld returned 1 exit status

Something in the SDK must have changed so that some new lib is introduced. lwip_src is indeed not present , just lwip.a.

Does anybody have  a clue how to add this to the toolchain? 

Regards
Gerry

**Comment by jantje** [comment] 2018-04-19 00:13
duplicate of #927

**Closed by jantje** 2018-04-19 00:13 UTC
Labels: status: duplicate
