### ISSUE TITLE
Platforms and Boards ordered incorrectly

### ISSUE THREAD

**Issue by rlogiacco** [Sloeber/arduino-eclipse-plugin#532] opened 2016-09-01 21:35 UTC
The way the "Platforms and Boards" list is displayed sorts the versions using string comparison, leading to a wrong sorting:
![image](https://cloud.githubusercontent.com/assets/199473/18185051/f693778c-709b-11e6-947c-b00ed21ec96d.png)

Solution is to parse the version number.
Also checking/unchecking the parent checkbox is (for a good reason) impossible: the visualization should be changed similarly to the libraries manager.

**Comment by jantje** [comment] 2016-09-02 11:04
When you are at it. can you also order the platforms?
The checkboxes are already mentioned in #398. Shall I close that as a duplicate of this one?
Note that the Manager class contains a Static compareVersions method taking 2 string.
I get confused quite often within this dialogbox (when there are plenty of boards installed) which is caused by the fact the package json file is not visible. This makes it possible there are 2 entries with the same name.

**Comment by rlogiacco** [comment] 2016-09-02 19:53
Regarding #398 I've assigned that too, no need to close as duplicate for now.
Regarding the Manager class I intend to refactor the whole thing to have one version parsing shared with the libraries, which is working.

**Comment by jantje** [comment] 2016-09-03 08:45
OK, Just don't undo my split from gui and controller in sloeber.io :-) and test the junit script :-)

**Comment by rlogiacco** [comment] 2016-09-03 13:56
@jantje ` which is caused by the fact the package json file is not visible`
Are you suggesting we should also show the package source file or just drop duplicates and pick only one of the two?

@jantje `can you also order the platforms?`
Any suggestion regarding the best ordering or just alpha (which, I believe, is already in place)?

**Comment by jantje** [comment] 2016-09-03 16:39
you can not drop duplicates as it is only the platform name that is duplicate. The boards may/are different

With me the platforms are not ordered case insensitive
![platform order](https://cloud.githubusercontent.com/assets/1175841/18226230/815046ba-7205-11e6-8daa-87e5db5153db.PNG)
- )

I would like to have the jason file visible one way or another. Maybe as a filter or just as part of the tree

**Comment by jantje** [comment] 2016-10-07 18:01
I have handled all the issues here.
Based on your library work :-)
![platform and boards ordering](https://cloud.githubusercontent.com/assets/1175841/19200341/d099e6c6-8cc8-11e6-8dd0-f8f18b854558.PNG)

**Closed** 2017-01-17 01:40 UTC
Labels: domain: gui, status: fixed in 4.0
