### ISSUE TITLE
known issues are not easy to find

### ISSUE THREAD

**Issue by larsskj** [Sloeber/arduino-eclipse-plugin#1122] opened 2019-12-30 11:03 UTC
I have written the following code as part of a project:

```
struct command {
	char code;
	int size;
	int (* callback)(char *inbuf);
	command *next { nullptr };
};

command *commands { nullptr };

command * getCommand(char code) {
	command *current = commands;

	while (current != nullptr && current->code != code && current->next) {
		current = current->next;
	}

	if (current != nullptr && current->code == code) {
		return current;
	} else {
		return nullptr;
	}
}
```

Whilst the code should be valid - it is as it compiles and runs using other tools - it won't compile using Sloeber.

Sloeber adds forward declarations to the file _sloeber.ino.cpp_ but only for the functions: The struct is missing from _sloeber.ino.cpp_ and the compiler stops with an error as the function _getCommand_ cannot return an unknown type.

Adding the struct to the top op the list in _sloeber.ino.cpp_ makes the project compile, but the struct is removed again whenever I modify the code.

**Comment by jantje** [comment] 2019-12-30 14:11
I guess this is a duplicate of #775 
Workaround: put the struct in a header file and include that in your ino file

**Comment by larsskj** [comment] 2019-12-30 17:05
Yes, this looks as a duplicate - sorry for not searching closed bugs.

**Comment by jantje** [comment] 2019-12-30 20:03
> 
> 
> Yes, this looks as a duplicate - sorry for not searching closed bugs.

No problem. It is logical to search only open issues. However it is annoying to keep "known issues" open.
To alleviate this I added links to github issues directly from Sloeber under the arduino menu item. But few people seem to find those.

**Comment by jantje** [comment] 2020-01-03 21:25
Seems I was mistaken and there is no "known issue" in the menu.
So I'll add it.

**Comment by jantje** [comment] 2020-01-03 21:49
@rlogiacco 
Can you provide a Italian translation for

command.know_limitations.info.label=Show the Known limitations of Sloeber ...
command.known_limitations.info.description=Opens a browser page that lists all known limitations (check before creating an issue)

**Closed** 2020-01-18 18:17 UTC
Labels: domain: documentation, status: fixed in nightly
