### ISSUE TITLE
Problem using Adafruit_LIS3DH - enum values are marked as 'redeclared'

### ISSUE THREAD

**Issue by judge2005** [Sloeber/arduino-eclipse-plugin#765] opened 2017-06-09 01:14 UTC
For example, in Adafruit_LIS3DH.h, this enum causes the compilation to fail (this is using the WeMos D1 R2 & mini toolchain):

typedef enum
{
  LIS3DH_AXIS_X         = 0x0,
  LIS3DH_AXIS_Y         = 0x1,
  LIS3DH_AXIS_Z         = 0x2,
} lis3dh_axis_t;

Has an error on each line.

**Comment by judge2005** [comment] 2017-06-09 01:28
Forget it. The header didn't have guards!

**Comment by jantje** [comment] 2017-06-09 09:31
This is a duplicate of #737 (however you will need to reinstall the libs to get it to work)
#737 is part of my lib improvement thread which is not yet in the nightly?
I need to do some serious testing on uploads because things have changed there to.

**Closed by jantje** 2017-06-09 09:31 UTC
Labels: status: duplicate
