### ISSUE TITLE
An internal error occurred

### ISSUE THREAD

**Issue by CaiNiaoLucifer** [Sloeber/arduino-eclipse-plugin#706] opened 2017-04-08 06:40 UTC
I downloaded V4.0_mac64.2017-01-17_15-14-48.tar.gz

and then extract it in /Application/ folder

An internal error occurred during: "Finishing the installation ..".
java.lang.NullPointerException

**Comment by jantje** [comment] 2017-04-08 09:55
This is probably a duplicate of #664 


As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Closed** 2017-04-12 20:22 UTC
Labels: status: duplicate
